{"name": "test_02_reg_failed1", "status": "passed", "description": "\n    1、已存在的账号注册失败\n    ", "start": 1609049302224, "stop": 1609049302378, "uuid": "a5dbb4dc-f183-430b-ba1b-f284f128a144", "historyId": "cbb0f6d1aa54d81493ff7437c9eb6a12", "testCaseId": "8fb79a2c83670dd422bc5a2619a78f49", "fullName": "case.test_02_regist#test_02_reg_failed1", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_02_regist"}, {"name": "host", "value": "LAPTOP-5O0J5MBG"}, {"name": "thread", "value": "38024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_02_regist"}]}